npm install -g @google/gemini-cli
gemini skills install https://github.com/vercel-labs/agent-skills
gemini skills install https://github.com/callstackincubator/agent-skills
gemini skills install https://github.com/google-labs-code/stitch-skills
gemini skills install https://github.com/google-labs-code/stitch-skills
gemini skills install https://github.com/google-labs-code/stitch-skills
gemini skills install https://github.com/google-labs-code/stitch-skills
gemini skills install https://github.com/google-labs-code/stitch-skills
gemini skills install https://github.com/google-labs-code/stitch-skills
gemini skills install https://github.com/google-labs-code/stitch-skills